"source ~/_vimrc

if has('gui_running')
  set lines=58
  set columns=190
"  set antialias
  set noimdisable
"  set guioptions=Mc

  colorscheme zenburn
  set background=dark
  " IMEオンでカーソルの色を変える
  if has('multi_byte_ime')
    highlight CursorIM guifg=NONE guibg=Green
  endif

  if has('win32')
    let &guifont=iconv('Osaka－等幅:h10.5:cSHIFTJIS', &encoding, 'cp932')
  else
    set transparency=2
    let &guifont=Osaka-Mono\ for\ Powerline:h15
  endif
endif

